[general]
import = ["~/.config/alacritty/colors.toml"]
live_config_reload = true

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[cursor.style]
blinking = "Never"

[terminal.shell]
program = "/usr/bin/zsh"

[terminal]

[window]
opacity = 0.85

[window.padding]
x = 12
y = 12
