[colors.primary]
background = "#0e1416"
foreground = "#f0f6f7"

[colors.cursor]
cursor = "#83d2e3"
text = "#0e1416"

[colors.selection]
background = "#2a3032"
foreground = "#f0f6f7"

[colors.normal]
black = "#0e1416"
blue = "#83d2e3"
cyan = "#60787e"
green = "#b1cbd1"
magenta = "#bcc5eb"
red = "#ffb4ab"
white = "#f0f6f7"
yellow = "#6a7395"

[colors.bright]
black = "#2a3032"
blue = "#83d2e3"
cyan = "#60787e"
green = "#b1cbd1"
magenta = "#bcc5eb"
red = "#ffb4ab"
white = "#bfc8cb"
yellow = "#6a7395"
