##############################

### WINDOWS AND WORKSPACES

##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {

name = suppress-maximize-events
match:class = .*

suppress_event = maximize
}

windowrule {

name = fix-xwayland-drags
match:class = ^$
match:title = ^$
match:xwayland = true
match:float = true
match:fullscreen = false
match:pin = false

no_focus = true
}

windowrule {
name = move-hyprland-run

match:class = hyprland-run

move = 20 monitor_h-120
float = yes
}

layerrule = match:namespace swaync-control-center, blur on
layerrule = match:namespace swaync-control-center, ignore_alpha 0.5

layerrule = match:namespace swaync-notification-window, blur on
layerrule = match:namespace swaync-notification-window, ignore_alpha 0.5

layerrule = match:namespace rofi, animation popin 90%
layerrule = match:namespace rofi, dim_around on

layerrule = match:namespace waybar, no_anim on
