# Font
font_family GeistMono Nerd Font Mono
font_size 15

disable_ligatures no

shell zsh
shell_integration disabled

url_style curly

# Catppuccin Mocha colors
background #1e1e2e
foreground #cdd6f4

selection_background #313244
selection_foreground #cdd6f4

cursor #f5e0dc
cursor_text_color #1e1e2e
cursor_blink_interval 0

# Normal colors
color0  #45475a
color1  #f38ba8
color2  #a6e3a1
color3  #f9e2af
color4  #89b4fa
color5  #cba6f7
color6  #94e2d5
color7  #bac2de

# Bright colors
color8  #585b70
color9  #f38ba8
color10 #a6e3a1
color11 #f9e2af
color12 #89b4fa
color13 #cba6f7
color14 #94e2d5
color15 #a6adc8

# Transparency for blur effect
background_opacity 0.85

# Slight fade for inactive windows
inactive_text_alpha 0.5


# Window
window_padding_width 12
window_margin_width 0
confirm_os_window_close 0

# Performance
repaint_delay 10
input_delay 0
sync_to_monitor no

# # Scrolling
# scrollback_lines 10000 no
