#############

### INPUT

#############

# https://wiki.hypr.land/Configuring/Variables/#input

input {
kb_layout = us
kb_variant =
kb_model =
kb_options =
kb_rules =

follow_mouse = 1

sensitivity = 0.5

touchpad {
    natural_scroll = true
}
}

# See https://wiki.hypr.land/Configuring/Gestures

gesture = 3, horizontal, workspace

# Example per-device config

# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

device {
name = epic-mouse-v1
sensitivity = -0.5
}

device {
    name = asup1204:00-093a:2642-touchpad
    enabled = true
}
