# Ref https://wiki.hypr.land/Configuring/Workspace-Rules/

# "Smart gaps" / "No gaps when only"

# uncomment all if you wish to use that.

# workspace = w[tv1], gapsout:0, gapsin:0

# workspace = f[1], gapsout:0, gapsin:0

# windowrule {

# name = no-gaps-wtv1

# match:float = false

# match:workspace = w[tv1]

#

# border_size = 0

# rounding = 0

# }

#

# windowrule {

# name = no-gaps-f1

# match:float = false

# match:workspace = f[1]

#

# border_size = 0

# rounding = 0

# }

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more

dwindle {
pseudotile = true
preserve_split = true
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more

master {
new_status = master
}

# https://wiki.hypr.land/Configuring/Variables/#misc

misc {
force_default_wallpaper = -1
disable_hyprland_logo = false
}
