###################

### MY PROGRAMS

###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use

$browser = zen-browser
$terminal = kitty
$fileManager = nautilus
# $menu = rofi -show drun -theme ~/.config/rofi/catppuccin.rasi
$menu = ~/.config/rofi/launchers/launcher.sh
