
$wall = $HOME/.config/hyprlock/wallpapers/2.png
$font = SF Pro Display Bold

############################
# GENERAL
############################
general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

############################
# BACKGROUND (GLASS BASE)
############################
background {
    monitor =
    path = $wall

    blur_passes = 4
    blur_size = 4

    contrast = 1
    brightness = 0.68
    vibrancy = 0.12
    vibrancy_darkness = 0.5

}

############################
# HUGE TIME — FULL SCREEN
# THIS IS THE "BACKGROUND"
############################
label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"


    font_family = $font

    # THIS is the key — bigger than screen height
    font_size = 400

    # very low opacity → behaves like background
    color = rgba(255, 255, 255, 0.57)

    halign = center
    valign = center

    # slight vertical bias looks better
    position = 0, 60
}

############################
# DATE — FOREGROUND, BOTTOM
############################
# label {
#     monitor =
#     text = cmd[update:60000] date +"%A • %d %B"

#     font_family = $font
#     font_size = 28

#     # foreground clarity
#     color = rgba(205, 214, 244, 0.85)

#     halign = center
#     valign = bottom

#     position = 0, 90
# }

############################
# SUBTLE GLASS STRIP (DATE)
############################
# shape {
#     monitor =
#     size = 520, 56
#     rounding = 28

#     color = rgba(255, 255, 255, 0.08)
#     border_size = 1
#     border_color = rgba(255, 255, 255, 0.14)

#     halign = center
#     valign = bottom
#     position = 0, 80
# }

############################
# INPUT FIELD (MINIMAL)
############################
input-field {
    monitor =
    size = 320, 52
    rounding = 26

    inner_color = rgba(255, 255, 255, 0.10)
    outer_color = rgba(255, 255, 255, 0.18)

    font_family = $font
    font_color = rgba(205, 214, 244, 0.9)

    placeholder_text =  unlock

    halign = center
    valign = bottom
    position = 0, 160
}
